---
repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt         # prebuilt upstream executable
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["-x", "-S", "warning"]  # -x: follow sources, -S warning: ignore info-level messages
  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible-lint
        entry: ansible-lint
        language: system
        files: \.(yml|yaml)$
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-ansible-vault
        name: Check Ansible Vault Encryption
        entry: bash check_ansible_vault.sh
        language: system
        files: (^|/)vault/.*$
        stages: [pre-commit]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0  # remplace par la dernière version stable
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
